### ISSUE TITLE
Etat des lieux de la documentation

### ISSUE THREAD

**Issue by caouecs** [laravel-france/OLD-laravel-france-doc#29]
Ce ticket sert à suivre les dernières évolutions de la traduction en gardant une trace du reste à faire. On y indique la date et numéro du dernier ticket côté dépôt officiel, pris en compte dans la traduction.

Date: 28/11/2013
Ticket : https://github.com/laravel/docs/commit/0aae3a7e49d2f1e856dd1a6bf1aca63e0e97d124

**Comment by JulienTant** [comment]
date : 16/09/2013
Ticket : https://github.com/laravel/docs/commit/be1a00f73a8c6d668c5c0783403da9f07f459842

**Comment by caouecs** [comment]
fait jusqu'au 23/09

**Comment by caouecs** [comment]
fait jusqu'au 26/09/2013

**Comment by JulienTant** [comment]
mis en prod today

**Comment by caouecs** [comment]
Date : 03/10/2013
Ticket : https://github.com/laravel/docs/commit/319c99ad0dd2c157ade922d9ae20385223cc1b8e

**Comment by caouecs** [comment]
Date : 12/10/2013
Ticket : https://github.com/laravel/docs/commit/3cf72b0276d0906719b3ba228dc0c8d992c7dc07

**Comment by JulienTant** [comment]
Mis en prod. Merci

**Comment by caouecs** [comment]
Date: 15/10/2013
Ticket : https://github.com/laravel/docs/commit/f55e4fb190d1756bafc514c7975b075637ebfb75

**Comment by JulienTant** [comment]
Date: 17/10/2013
Ticket : https://github.com/laravel/docs/commit/aaabc06ffdf18ced06b199df8d0138a01c9dd4b0

tu l'as visiblement déjà fait !

**Comment by caouecs** [comment]
oui, j'ai eu la fainéantise de rajouter un commentaire, et je n'ai mis que le premier post à jour

**Comment by caouecs** [comment]
Date: 29/10/2013
Ticket : https://github.com/laravel/docs/commit/6460895510ea29cc84422aaf7425bbf382a7636e

**Comment by caouecs** [comment]
Date: 30/10/2013
Ticket : https://github.com/laravel/docs/commit/7a041a4685a537b0509bbeb8d999bf36ada22b84

**Comment by JulienTant** [comment]
C'est en prod !

**Comment by caouecs** [comment]
Date: 31/10/2013
Ticket : https://github.com/laravel/docs/commit/dfc720d144e60399ffe1d493b8b7d7887526b1d6

**Comment by caouecs** [comment]
Date: 06/11/2013
Ticket : https://github.com/laravel/docs/commit/91ba40cdf073bcc26d01907ee34f84560ed8e35f

**Comment by caouecs** [comment]
Date: 07/11/2013
Ticket : https://github.com/laravel/docs/commit/9fabb11bcd1ac832e9772c3b66683acfee8c2a66

**Comment by caouecs** [comment]
Date: 12/11/2013
Ticket : https://github.com/laravel/docs/commit/756816ebcf22ccd0a65125e74010840498908ee8

**Comment by caouecs** [comment]
Date: 20/11/2013
Ticket : https://github.com/laravel/docs/commit/346e9af34ce2bf7059b6c21c42989dcc3f0497f1

**Comment by caouecs** [comment]
Date: 28/11/2013
Ticket : https://github.com/laravel/docs/commit/0aae3a7e49d2f1e856dd1a6bf1aca63e0e97d124

**Comment by JulienTant** [comment]
Encore merci pour l'investissement :)

**Comment by caouecs** [comment]
Pas de soucis, je me suis bien amusé, et le Meetup Laravel auquel j'avais participé était vraiment sympa ;)
